name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: '2.6.10'
            rails-version: '6.0.0'
          - ruby-version: '2.6.10'
            rails-version: '6.1.0'
          - ruby-version: '3.2'
            rails-version: '7.0.0'

    env:
      RAILS_VERSION: ${{ matrix.rails-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run tests
        run: bundle exec rake

